using System.Reflection;
//
//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.573
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
//
[assembly: AssemblyProduct("TourWriter")]
[assembly: AssemblyCopyright("Copyright (c) 2009")]
[assembly: AssemblyVersion("0")]
[assembly: AssemblyFileVersion("")]
[assembly: AssemblyInformationalVersion("Development version")]