using System.Reflection;
//
//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.573
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
//
[assembly: AssemblyProduct("TourWriter")]
[assembly: AssemblyCopyright("Copyright (c)")]
[assembly: AssemblyVersion("9999.0")]
[assembly: AssemblyFileVersion("9999.0.0.0")]
[assembly: AssemblyInformationalVersion("9999.0.0.0")]