//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourWriter {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TourWriter.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to close?.
        /// </summary>
        internal static string AskCloseApp {
            get {
                return ResourceManager.GetString("AskCloseApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data does not exist, would you like to create it?.
        /// </summary>
        internal static string AskCreateRow {
            get {
                return ResourceManager.GetString("AskCreateRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This booking is now empty, do you want to delete the booking also?.
        /// </summary>
        internal static string AskDeleteEmptyBooking {
            get {
                return ResourceManager.GetString("AskDeleteEmptyBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This row should be disabled rather than deleted. Do you still with to delete it?.
        /// </summary>
        internal static string AskDeleteOrDisableRow {
            get {
                return ResourceManager.GetString("AskDeleteOrDisableRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this item?.
        /// </summary>
        internal static string AskDeleteRow {
            get {
                return ResourceManager.GetString("AskDeleteRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save changes?.
        /// </summary>
        internal static string AskDoSave {
            get {
                return ResourceManager.GetString("AskDoSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item date is not within the valid date range for this service. Do you want to continue?.
        /// </summary>
        internal static string AskInvalidPurchaseItemDate {
            get {
                return ResourceManager.GetString("AskInvalidPurchaseItemDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: All data changes since this backup file was made will be lost! Do you wish to proceed?.
        /// </summary>
        internal static string AskRestoreDatabase {
            get {
                return ResourceManager.GetString("AskRestoreDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;&lt; Less.
        /// </summary>
        internal static string Less {
            get {
                return ResourceManager.GetString("Less", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TourWriter Message.
        /// </summary>
        internal static string MessageCaption {
            get {
                return ResourceManager.GetString("MessageCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More &gt;&gt;.
        /// </summary>
        internal static string More {
            get {
                return ResourceManager.GetString("More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: Itinerary Price Override exists ({0}) and should be updated to reflect this change.
        ///    
        ///Do you want to remove the override now?
        ///.
        /// </summary>
        internal static string PriceOverrideConflict {
            get {
                return ResourceManager.GetString("PriceOverrideConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAILED: The backup process was not successful..
        /// </summary>
        internal static string ShowDatabaseBackupFailed {
            get {
                return ResourceManager.GetString("ShowDatabaseBackupFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The database was successfully backed up..
        /// </summary>
        internal static string ShowDatabaseBackupSuccess {
            get {
                return ResourceManager.GetString("ShowDatabaseBackupSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAILED: The restore process was not successful..
        /// </summary>
        internal static string ShowDatabaseRestoreFailed {
            get {
                return ResourceManager.GetString("ShowDatabaseRestoreFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The database was successfully restored..
        /// </summary>
        internal static string ShowDatabaseRestoreSuccess {
            get {
                return ResourceManager.GetString("ShowDatabaseRestoreSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to add the data..
        /// </summary>
        internal static string ShowDragDropFailed {
            get {
                return ResourceManager.GetString("ShowDragDropFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File or folder could not be found; either the folder path or file name is incorrect, or access was blocked..
        /// </summary>
        internal static string ShowFileNotFound {
            get {
                return ResourceManager.GetString("ShowFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your TourWriter license has expired. Please contact TourWriter.com.
        /// </summary>
        internal static string ShowLicenseExpired {
            get {
                return ResourceManager.GetString("ShowLicenseExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your TourWriter license will expire in {0} days. Please update your license before that time, as TourWriter will cease to function..
        /// </summary>
        internal static string ShowLicenseExpiring {
            get {
                return ResourceManager.GetString("ShowLicenseExpiring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login failed for that username and password..
        /// </summary>
        internal static string ShowLoginFailed {
            get {
                return ResourceManager.GetString("ShowLoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum number of logins has been reached for your TourWriter license..
        /// </summary>
        internal static string ShowMaxLoginsReached {
            get {
                return ResourceManager.GetString("ShowMaxLoginsReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results were found for that search..
        /// </summary>
        internal static string ShowNoSearchData {
            get {
                return ResourceManager.GetString("ShowNoSearchData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This function is not yet implimented..
        /// </summary>
        internal static string ShowNotImplimented {
            get {
                return ResourceManager.GetString("ShowNotImplimented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The passwords entered do not match, please re-enter..
        /// </summary>
        internal static string ShowPasswordMismatch {
            get {
                return ResourceManager.GetString("ShowPasswordMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password entered is not valid, please re-enter..
        /// </summary>
        internal static string ShowPasswordNotValid {
            get {
                return ResourceManager.GetString("ShowPasswordNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your current permission level does not allow this action..
        /// </summary>
        internal static string ShowPermissionDenied {
            get {
                return ResourceManager.GetString("ShowPermissionDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The row has already been added..
        /// </summary>
        internal static string ShowRowAlreadyExists {
            get {
                return ResourceManager.GetString("ShowRowAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No row selected to add new data to..
        /// </summary>
        internal static string ShowRowNotSelected {
            get {
                return ResourceManager.GetString("ShowRowNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to connect to database server..
        /// </summary>
        internal static string ShowServerNotFound {
            get {
                return ResourceManager.GetString("ShowServerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your user account has been disabled..
        /// </summary>
        internal static string ShowUserAccountDisabled {
            get {
                return ResourceManager.GetString("ShowUserAccountDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value of &apos;{0}&apos; is not valid, please re-enter..
        /// </summary>
        internal static string ShowValueNotValid {
            get {
                return ResourceManager.GetString("ShowValueNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Services are not yet implimented..
        /// </summary>
        internal static string ShowWebNotImplimented {
            get {
                return ResourceManager.GetString("ShowWebNotImplimented", resourceCulture);
            }
        }
    }
}
